-- forum_schema.sql
-- PostgreSQL用 安全スキーマ

-- threadテーブル
CREATE TABLE IF NOT EXISTS public.thread (
    thread_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    deleted boolean NOT NULL,
    created_at timestamp(6) without time zone,
    title character varying(255),
    PRIMARY KEY(thread_id)
);

-- postテーブル
CREATE TABLE IF NOT EXISTS public.post (
    content_id bigint NOT NULL,
    thread_id bigint,
    deleted boolean NOT NULL,
    created_at timestamp(6) without time zone,
    author_name character varying(255),
    content character varying(255),
    PRIMARY KEY(content_id, thread_id),
    CONSTRAINT fk_post_thread FOREIGN KEY(thread_id) REFERENCES public.thread(thread_id)
);

-- 権限
ALTER TABLE IF EXISTS public.thread OWNER TO forumuser;
ALTER TABLE IF EXISTS public.post OWNER TO forumuser;

-- users テーブル
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,  -- BCryptでハッシュ化
    enabled BOOLEAN DEFAULT true
);

-- roles テーブル
CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL  -- 例: 'ROLE_ADMIN', 'ROLE_USER'
);

-- users-roles テーブル
CREATE TABLE user_roles (
    user_id INT REFERENCES users(id),
    role_id INT REFERENCES roles(id),
    PRIMARY KEY (user_id, role_id)
);
