# .github/workflows/ci.yml

name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ソースコードをチェックアウト
      uses: actions/checkout@v4

    - name: JDKをセットアップ
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # or '11' or whatever your project uses

    - name: Gradle Wrapperに実行権限を付与
      run: chmod +x ./gradlew

    - name: ビルドとテストの実行
      run: ./gradlew build
